### ISSUE TITLE
Miles ?

### ISSUE THREAD

**Issue by danitalia1** [DrieStone/TeslaFi-Widget#2]
![96862174-C502-4390-BB11-FF5E643A6C76](https://user-images.githubusercontent.com/73533358/97303717-0c287280-185b-11eb-9eb6-a3312e1a2ae0.jpeg)
Hey :)! 

Great widget !! Would it be possible to maybe also to offer the widget, to maybe display KM instead Miles ? 

My car displays only miles even if there is KM written, would that be possible ? 

Thanky ou so much!

**Comment by screamer3003** [comment]
You can add the factor * 1.609 in the script and you have the range in km. It will look so 

if (show_range_est) { 
			batteryCurrentCharge = Math.floor(items.est_battery_range * 1.609)+units

**Comment by danitalia1** [comment]
Great! 
That worked fine !! Just perfect!

**Comment by DrieStone** [comment]
I didn't test this earlier, and I assumed the value returned by the API would match the label. I've rolled this change into the code as well, so future users shouldn't have this problem.
